### ISSUE TITLE
Не коннектится приложение по блютус

### ISSUE THREAD

**Issue by amlist-sun** [Skiff2/SkiffDRO#3]
Собрал тестовый стенд с ардуиной и блютус-модулем, накидал скетч, установил программку на андроид, а она не коннектится.
https://stackoverflow.com/questions/76480490/is-device-getclass-getmethodcreaterfcommsocket-int-class-not-working-any
Походу что-то такое же.
Есть ли вариант выложить исходники токарного приложения?

**Comment by Skiff2** [comment]
https://github.com/Skiff2/SkiffDRO_AVS

Развлекайтесь =) Но желательно скинуть пул-реквест по решению

**Comment by amlist-sun** [comment]
Большое спасибо. Теперь пойду налаживать среду для андроидной разработки. Попробую пульнуть как выйдет.
